[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Specify the serial port (adjust for your system)
monitor_speed = 115200

; Libraries required for this project
lib_deps =
    marvinroger/AsyncMqttClient@^0.9.0
    ESP32Async/AsyncTCP@^1.1.1
    ESP32Async/ESPAsyncWebServer@^1.3.3
    Ayush Sharma/ElegantOTA@^2.2.9
    Adafruit DHT sensor library@^1.4.4
    Adafruit Unified Sensor@^1.1.14
    NTPClient@^3.2.1
